[env]
TERM = "xterm-256color"

[window]
padding = { x = 0, y = 0 }
dynamic_padding = true

[scrolling]
history = 100000

[font]
# normal = { family = "Iosevka", style = "Regular" }
# normal = { family = "Iosevka Nerd Font", style = "Regular" }
normal = { family = "Fira Mono", style = "Regular" }
